"""
Even Fibonacci numbers
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


# Initialize the fib_list start
fib_list = [1,2]

# Fill out the fib_list with fib sequence
i = 0
while i < int(4e6):
    list_len = len(fib_list)
    i = fib_list[list_len-1] + fib_list[list_len-2]
    fib_list.append(i)

# Get only even terms
even_fib_list = [x for x in fib_list if x%2==0]

print(sum(even_fib_list))
# 4613732